import uuid
from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


class WorldState(BaseModel):
    """
    Represents the environment/temporal context of the system.
    """
    current_date: str = Field(..., description="Today's date in YYYY-MM-DD format.")
    current_time: str = Field(..., description="Current system time.")
    day_of_week: str = Field(..., description="Full day name.")
    system_era: str = Field("2026 (Agentic Reasoning Era)", description="The operational era.")
    knowledge_cutoff: str = Field("2024", description="The approximate training cutoff of sub-agents.")


class AtomicTask(BaseModel):
    """
    The strict contract representing a task decomposed by IntentOrchestrator (IO).
    AgentSynthesizer (AS) uses this to fetch and arm the correct Sub-agent.
    """
    id: str = Field(..., description="Unique identifier for the task.")
    description: str = Field(..., description="Detailed description of what needs to be done.")
    required_capabilities: list[str] = Field(
        ..., 
        description="Core capabilities needed (e.g., 'search', 'python_execution')."
    )
    context_keys: list[str] = Field(
        default_factory=list, 
        description="Keys to extract from the global Blackboard State to inject as context."
    )
    depends_on: list[str] = Field(
        default_factory=list,
        description="List of task IDs that must be completed before this task can start."
    )
    required_keys: list[str] = Field(
        default_factory=list,
        description="Blackboard keys required to be present before this task is scheduled."
    )
    branch_policy: str = Field(
        default="overwrite",
        description="Merge strategy: 'overwrite', 'append', or 'semantic_merge'."
    )
    expected_output: str = Field(..., description="What the Sub-agent is expected to return.")

class SubAgentResult(BaseModel):
    """
    The result returned by a Sub-agent back to the IO.
    """
    task_id: str = Field(..., description="The ID of the task being completed.")
    status: str = Field(..., description="Result status: 'success', 'failure', or 'error'.")
    output: str = Field(..., description="The actual output or error message from the sub-agent.")
    artifacts: dict[str, Any] = Field(
        default_factory=dict, 
        description="Any structured artifacts produced during execution."
    )

class TrajectoryStep(BaseModel):
    """
    A single step in the execution history, used by the EvolutionaryOptimizer (EO) for reflection.
    """
    step_id: int = Field(..., description="The sequence number of the step.")
    task: AtomicTask = Field(..., description="The task that was executed.")
    result: SubAgentResult = Field(..., description="The result of the task execution.")
    parent_ids: list[str] = Field(default_factory=list, description="IDs of tasks this step depended on.")
    sibling_ids: list[str] = Field(default_factory=list, description="IDs of tasks running concurrently with this one.")
    timestamp: datetime = Field(default_factory=datetime.now, description="When the step occurred.")

class Skill(BaseModel):
    """
    A distilled piece of procedural knowledge (SOP) generated by EO.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    title: str = Field(..., description="Short, descriptive title of the skill.")
    description: str = Field(..., description="When should this skill be applied?")
    content_markdown: str = Field(..., description="The actual SOP or instructions in Markdown.")
    vector_embedding: list[float] | None = Field(None, description="Vector representation for semantic search.")

class GlobalState(BaseModel):
    """
    The Blackboard Pattern implementation. Shared state across the task lifecycle.
    """
    session_id: str = Field(..., description="Unique session ID.")
    original_intent: str = Field(..., description="The user's original goal.")
    world_state: WorldState | None = Field(None, description="Temporal and environment context.")
    todo_list: list[AtomicTask] = Field(default_factory=list)
    completed_tasks: list[AtomicTask] = Field(default_factory=list)
    shared_memory: dict[str, Any] = Field(
        default_factory=dict, 
        description="Key-Value store for context sharing between Sub-agents."
    )
    trajectory: list[TrajectoryStep] = Field(
        default_factory=list, 
        description="The execution path for EO to analyze."
    )
    status: str = Field(
        default="running", 
        description="Current orchestration status: 'running', 'completed', 'failed'."
    )

class IOPlan(BaseModel):
    """Structured output for IO Planner."""
    tasks: list[AtomicTask]

class EOSkillExtract(BaseModel):
    """Structured output for EO Reflection."""
    skip: bool = Field(..., description="True if the trajectory yielded no new valuable skills.")
    title: str = Field(default="", description="Short title of the new skill.")
    description: str = Field(default="", description="Description of when to apply the skill.")
    content_markdown: str = Field(default="", description="The step-by-step SOP.")
